//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char clock [] = {
0x3C, 0x42, 0x81, 0x99, 0x89, 0x89, 0x42, 0x3C, 
};
