
//WARNING: This Font Require X-GLCD Lib.
//         You can not use it with MikroE GLCD Lib.

//Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
//MikroElektronika 2011
//http://www.mikroe.com

//GLCD FontName : System12x12
//GLCD FontSize : 12 x 12

#ifndef DaysOfWeek12x12_H_INCLUDED
#define DaysOfWeek12x12_H_INCLUDED

extern const uint8_t DaysOfWeek12x12[] PROGMEM;

#endif