
//WARNING: This Font Require X-GLCD Lib.
//         You can not use it with MikroE GLCD Lib.

//Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
//MikroElektronika 2011
//http://www.mikroe.com

//GLCD FontName : System16x22
//GLCD FontSize : 16 x 22

#ifndef SYSTEM16x22_H_INCLUDED
#define SYSTEM16x22_H_INCLUDED

extern const uint8_t System16x22[] PROGMEM;

#endif
